### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by metulburr** [WildcardSearch/YourCode#13]
I came here from this thread
https://community.mybb.com/thread-134038-post-1246127.html#pid1246127

Im trying to restrict post icons to certain user groups. I have no idea how to use this mod, or to modify it. When i enabled it, some of the original BBcode broke and just shows BBcode within the post now.

IS there a how to use this plugin?

**Comment by WildcardSearch** [comment]
This plugin cannot restrict the use of post icons for certain users or groups.
